config/routes.rb
ActionController::Routing::Routes.draw do |map|
  map.root :controller => "welcome"
  map.forgot_password '/forgot_password',       :controller => 'users',    :action => 'forgot_password'
  map.reset_password  '/reset_password/:id',    :controller => 'users',    :action => 'reset_password'  
  map.change_password '/change_password/:id',   :controller => "users",    :action => 'change_password'
  map.logout          '/logout',                :controller => 'sessions', :action => 'destroy'
  map.login           '/login',                 :controller => 'sessions', :action => 'new'
  map.search          '/search/:action',                :controller => "search"
  map.activate        '/activate/:activation_code', :controller => 'users', :action => 'activate', :activation_code => nil
  map.employees_search_results '/employees/search_results', :controller => "employees", :action => "search_results"
  map.locations_search_results '/locations/search_results', :controller => "locations", :action => "search_results"
  map.phones_search_results    '/phones/search_results',    :controller => "phones",    :action => "search_results"
  map.save_primaries  '/save_primaries', :controller => 'master_relations', :action => 'save_primaries'  
  map.edit_component '/edit_component/:id/:component', :controller => 'master_relations', :action => 'edit_component'
  map.delete_component '/delete_component/:id/:component', :controller => 'master_relations', :action => 'delete_component'
  map.add_component '/add_component/:id/:component', :controller => 'master_relations', :action => 'add_component'
  map.unsent_changes  '/audits/unsent_changes', :controller => 'audits', :action => 'unsent_changes'
  map.send_changes    '/audits/send_changes',   :controller => 'audits', :action => 'send_changes'
  map.reports         '/reports/:action',               :controller => 'reports'
  map.reports_search_results '/reports/search_results', :controller => 'reports', :action => 'search_results'
  map.division_employees '/division_employees/:id', :controller => 'employees', :action => 'division_employees'
  map.incorrect_information '/incorrect_information', :controller => 'feedbacks', :action => 'incorrect_information'
  map.add_employee_search_results '/add_employee_search_results', :controller => 'master_relations', :action => 'add_employee_search_results'
  map.add_location_search_results '/add_location_search_results', :controller => 'master_relations', :action => 'add_location_search_results'
  map.add_phone_search_results '/add_phone_search_results', :controller => 'master_relations', :action => 'add_phone_search_results'
  map.delete_phone    '/phones/:id/delete', :controller => 'phones', :action => 'destroy'
  map.connect         '/search/find_employees', :controller => 'search',    :action => 'find_employees'
  map.connect         '/users/search_results_for_user_add',  :controller => 'users', :action => 'search_results_for_user_add'
  map.connect         '/users/add_employee/:id',:controller => 'users',     :action => 'add_employee'
  map.connect         '/employees/last_names',  :controller => "employees", :action => "last_names"
  map.connect         '/employees/first_names', :controller => "employees", :action => "first_names"
  map.connect         '/counties/names',        :controller => "counties",  :action => "names"
  map.connect         '/buildings/cities',      :controller => "buildings", :action => "cities"  
  map.connect         '/buildings/zip_codes',   :controller => "buildings", :action => "zip_codes"  
  map.connect         '/locations_manager',     :controller => 'locations_manager', :action => 'index'
  map.connect         '/employees/search.:format',     :controller => 'employees', :action => 'search'
  map.full_data_report '/reports/full_data_report.:format',     :controller => 'reports', :action => 'full_data_report'
  map.resources :locations
  map.resources :phones
  map.resources :campuses, :singular => :campus
  map.resources :buildings
  map.resources :counties
  map.resources :employees
  map.resources :master_relations
  map.resources :users, :except => [:new], :member => {:delete => :get}
  map.resource :session
  map.connect '/:controller/:action/:id'
end

app/models/user.rb
require 'digest/sha1'

class User < ActiveRecord::Base
  
  belongs_to :employee
  include Authentication
  include Authentication::ByPassword
  include Authentication::ByCookieToken
  after_create :assign_default_roles
  delegate :email, :to => :employee
  # ---------------------------------------
  # The following code has been generated by role_requirement.
  # You may wish to modify it to suit your need
  has_and_belongs_to_many :roles
  
  before_create :make_activation_code
  
  validates_length_of       :login,    :within => 3..40
  validates_format_of       :login,    :with => Authentication.login_regex, :message => Authentication.bad_login_message
  
  validates_associated      :employee
  validates_presence_of     :employee_id
  
 
  # validates_length_of       :password, :within => 6..50, :on => [:change_password], 
  #                                      :message => 'The length of your password must be between 6 and 50 characters.'
  #                                
  # validates_length_of       :password_confirmation, :within => 6..50, :on => [:change_password], 
  #                                      :message => 'The length of your password must be between 6 and 50 characters.'

  # prevents a user from submitting a crafted form that bypasses activation
  # anything else you want your user to change should be added here.
  attr_accessible :login, 
                  :password, 
                  :password_confirmation,
                  :employee_id,
                  :recently_saved,
                  :recently_forgot,
                  :recently_reset,
                  :activated_at,
                  :activation_code

  
  attr_accessor   :four_11_phone
                  
  def assign_default_roles
    self.roles << Role.find_by_name('Read Only')
  end

  def has_role?(role_in_question)
    @roles_list ||= self.roles.collect(&:name)
    return true if @roles_list.include?("admin")
    (@roles_list.include?(role_in_question.to_s) )
  end
  
  def name
    employee.full_name
  end
  # Authenticates a user by their login name and unencrypted password.  Returns the user or nil.
  #
  # uff.  this is really an authorization, not authentication routine.  
  # We really need a Dispatch Chain here or something.
  # This will also let us return a human error message.
  #
  def self.authenticate(login, password)
    return nil if login.blank? || password.blank?
    u = find :first, :conditions => ['login = ? and activated_at IS NOT NULL', login] # need to get the salt
    u && u.authenticated?(password) ? u : nil
  end
  
  def self.application_users
    self.find(:all, :conditions => ["login != ''"], :include => 'roles', :order => "last_name" )
  end
  
  def login=(value)
    write_attribute :login, (value ? value.downcase : nil)
  end


  def create_from_employee
    
    @recently_created = true
  end
  
  def forgot_password
    @recently_forgot = true
    self.make_password_reset_code
  end

  def reset_password
    # First update the password_reset_code before setting the 
    # reset_password flag to avoid duplicate e-mail notifications.
    update_attributes(:password_reset_code => nil)
    @recently_reset = true
  end  

  #used in user_observer
  def recently_forgot_password?
    @recently_forgot
  end
  
  def recently_reset_password?
    @recently_reset
  end
  
  def recently_created?
    @recently_created
  end
  
  def self.create_from employee
    user = self.new
    user.employee = employee
    user.login = employee.people_first_user
    user.password = user.password_confirmation = APP_CONFIG['settings']['initial_pwd']
    user.create_from_employee
    user.save!
    user
  end

  # Activates the user in the database.
  def activate!
    @activated = true
    self.activated_at = Time.now.utc
    self.activation_code = nil
    save(false)
  end

  # Returns true if the user has just been activated.
  def recently_activated?
    @activated
  end

  def active?
    # the existence of an activation code means they have not activated yet
    activation_code.nil?
  end

protected
  def make_password_reset_code
    self.password_reset_code = Digest::SHA1.hexdigest( Time.now.to_s.split(//).sort_by {rand}.join )
  end
    def make_activation_code
      self.activation_code = self.class.make_token
    end

end

app/helpers/users_helper.rb
module UsersHelper
  
  #
  # Use this to wrap view elements that the user can't access.
  # !! Note: this is an *interface*, not *security* feature !!
  # You need to do all access control at the controller level.
  #
  # Example:
  # <%= if_authorized?(:index,   User)  do link_to('List all users', users_path) end %> |
  # <%= if_authorized?(:edit,    @user) do link_to('Edit this user', edit_user_path) end %> |
  # <%= if_authorized?(:destroy, @user) do link_to 'Destroy', @user, :confirm => 'Are you sure?', :method => :delete end %> 
  #
  #
  def if_authorized?(action, resource, &block)
    if authorized?(action, resource)
      yield action, resource
    end
  end

  #
  # Link to user's page ('users/1')
  #
  # By default, their login is used as link text and link title (tooltip)
  #
  # Takes options
  # * :content_text => 'Content text in place of user.login', escaped with
  #   the standard h() function.
  # * :content_method => :user_instance_method_to_call_for_content_text
  # * :title_method => :user_instance_method_to_call_for_title_attribute
  # * as well as link_to()'s standard options
  #
  # Examples:
  #   link_to_user @user
  #   # => <a href="/users/3" title="barmy">barmy</a>
  #
  #   # if you've added a .name attribute:
  #  content_tag :span, :class => :vcard do
  #    (link_to_user user, :class => 'fn n', :title_method => :login, :content_method => :name) +
  #          ': ' + (content_tag :span, user.email, :class => 'email')
  #   end
  #   # => <span class="vcard"><a href="/users/3" title="barmy" class="fn n">Cyril Fotheringay-Phipps</a>: <span class="email">barmy@blandings.com</span></span>
  #
  #   link_to_user @user, :content_text => 'Your user page'
  #   # => <a href="/users/3" title="barmy" class="nickname">Your user page</a>
  #
  def link_to_user(user, options={})
    raise "Invalid user" unless user
    options.reverse_merge! :content_method => :login, :title_method => :login, :class => :nickname
    content_text      = options.delete(:content_text)
    content_text    ||= user.send(options.delete(:content_method))
    options[:title] ||= user.send(options.delete(:title_method))
    link_to h(content_text), change_password_path(user), options
  end

  #
  # Link to login page using remote ip address as link content
  #
  # The :title (and thus, tooltip) is set to the IP address 
  #
  # Examples:
  #   link_to_login_with_IP
  #   # => <a href="/login" title="169.69.69.69">169.69.69.69</a>
  #
  #   link_to_login_with_IP :content_text => 'not signed in'
  #   # => <a href="/login" title="169.69.69.69">not signed in</a>
  #
  def link_to_login_with_IP content_text=nil, options={}
    ip_addr           = request.remote_ip
    content_text    ||= ip_addr
    options.reverse_merge! :title => ip_addr
    if tag = options.delete(:tag)
      content_tag tag, h(content_text), options
    else
      link_to h(content_text), login_path, options
    end
  end

  #
  # Link to the current user's page (using link_to_user) or to the login page
  # (using link_to_login_with_IP).
  #
  def link_to_current_user(options={})
    if current_user
      link_to_user current_user, options
    else
      content_text = options.delete(:content_text) || 'not signed in'
      # kill ignored options from link_to_user
      [:content_method, :title_method].each{|opt| options.delete(opt)} 
      link_to_login_with_IP content_text, options
    end
  end

end

app/views/users/_user_bar.html.haml
- if logged_in?
  #user-bar-greeting='Logged in as '+ link_to(current_user.name, change_password_path(:id => current_user.id), { :title => "Change password" })
  #user-bar-action=link_to("Log out", logout_path, { :title => "Log out" })
- else
  #user-bar-greeting= link_to_login_with_IP('Not logged in', :style => 'border: none;')
  #user-bar-action= link_to( "Log in",  login_path,  { :title => "Log in" })

app/views/users/change_password.html.haml
.form(style='width: 350px; margin: auto')
  %p.strong
    Changing the password for:
    %br
    = current_user.employee.full_name
  - form_for current_user, :url => {:action => 'change_password'} do |f|
    %p.field
      %label.block{ :for => "password", :style => 'width: 140px' }
        New Password
      = password_field_tag 'password', {}, :size => 25, :class => 'text'
      %br
      %small Between 6 and 40 characters
    %p.field
      %label.block{ :for => "password_confirmation" , :style => 'width: 140px'}
        Confirm new password
      = password_field_tag 'password_confirmation', {}, :size => 25, :class => 'text'
    %p.center
      = submit_tag 'Change password'

app/views/users/edit.html.haml
%h1='Editing: '+@user.employee.full_name
- form_for @user do |f|
  Roles:
  -@roles.each do |role|
    %p.wide
      %label= role.name
      = check_box_tag "user[role_ids][]", role.id, @user.has_role?(role.name)
  %p
    =f.submit "Save #{@user.employee.full_name}"

app/views/users/forgot_password.html.erb
     <h1>Password Reset Request</h1>
    <% form_for :user, :url => {:action => 'forgot_password'} do |form| %>
        <fieldset>
         <p>Enter the e-mail address that you have on file with People First. We will 
         send you a password reset link to that e-mail address.</p>
            <p>
                <label for="user_email" >E-mail Address:</label><br/>
                <%= form.text_field :email, :size => 35, :class => 'text' %>
            </p>
            <%= submit_tag 'Send' %>
        </fieldset>
    <% end %> 

app/views/users/index.html.haml
%div{:class => (logged_in? && current_user.has_role?('Administrator')) ? 'yui-ge' : ''}
  %div{:class => (logged_in? && current_user.has_role?('Administrator')) ? 'yui-u first' : ''}  
    .form
      %h1 Application Users
      %table#application_users.results
        %thead
          %tr
            %th{:rowspan => 2} Name
            %th{:rowspan => 2} Phone number
            %th{:rowspan => 2} E-mail
            %th{:colspan => 2} Roles
            -if logged_in? && current_user.has_role?('Administrator')
              %th{:colspan => 2, :rowspan => 2}
          %tr
            %th Admin
            %th Read only
  
        %tbody
          -@users.each do |u|
            %tr{ :class => cycle('odd', 'even')}
              %td= (u == current_user) ? link_to( u.employee.full_name, change_password_url(u.id), :class => 'simple_ajax_dialog') : u.employee.full_name
              %td=u.four_11_phone.to_label if u.four_11_phone
              %td=u.employee.email
              %td{:class => u.has_role?('Administrator') ? 'true': 'false'}
              %td{:class => u.has_role?('Read Only') ? 'true': 'false'}
              -if logged_in? and current_user.has_role?('Administrator')
                %td=(u.employee.active_flag?) ? link_to('Edit', edit_user_path(:id => u.id), :class => 'simple_ajax_dialog') : link_to(image_tag('invalid.png',:alt => 'Invalid'), {:controller => 'employees', :action => 'why_invalid', :id => u.employee.id }, :class => 'simple_ajax_dialog')
                %td=link_to image_tag('delete.png', :alt => 'Delete User'), delete_user_path(u.id), :class => 'confirm_action_dialog', :title => 'delete this user'
  -if logged_in? and current_user.has_role?('Administrator')
    .yui-u
      .form
        %h1 Add Users
        =render :partial => 'search/find_employees', :locals => {:employee_to_search => @search_params, :destination => @search_results_for_user_add, :html_results => @html_results, :ac => ' omit_users'}

app/views/users/reset_password.html.haml
.form{:style => 'margin:10px auto;width:350px;'}
  -if @user
    - form_for :user, :url => {:action => "reset_password"} do |form|
      %h1="Hello #{@user.employee.full_name}."
      %p Thank you for changing your password!
      %p
        %label{ :for => "user_password" }
          New password:
        %br
        = form.password_field :password, :size => 45, :class => 'text'
      %p
        %label{ :for => "user_password_confirmation" }
          Confirm your new password:
        %br
        = form.password_field :password_confirmation, :size => 45, :class => 'text'
      = submit_tag "Change password"
  -else
    %p Sorry, we could not find a user with the link you provided.
    %p Please check the following:
    %ul
      %li Check that you have entered the full link in web address bar.
      %li Check that you are using the most recent email we sent you. 
    %p
      If the above steps do not solve the ploblem, please contact applications support at the following address:
      =mail_to APP_CONFIG['mail']['apps_support'], APP_CONFIG['mail']['apps_support'], :subject => @mail_subject, :body => @mail_body

app/views/users/search_results_for_user_add.html.haml
-if @employees.size == 0
  %h1 No employees found
  %p Sorry, no employees match that criteria.
  %p Please try broadening your search criteria.
-else
  %h1 Select a user to add:
  %table#add_users.results
    %thead
      %tr
        %th Name
        %th E-mail
        %th Add
    %tbody
      -@employees.each do |e|
        %tr{:class => cycle('odd', 'even')}
          %td=e.full_name
          %td=e.email unless e.email.blank?
          %td
            -if e.valid?
              =link_to image_tag('add.png',:alt => 'Add'), {:controller => 'users', :action => 'add_employee', :id => e.id }, :class => 'confirm_action_dialog', :title => 'add this user'
            -else
              =link_to image_tag('invalid.png',:alt => 'Invalid'), {:controller => 'employees', :action => 'why_invalid', :id => e.id }, :class => 'simple_ajax_dialog'

app/views/users/show.html.haml
%span.title=@user.full_name
%p="Name: "+@user.full_name
%p="E-mail: "+@user.email
%p='Phone: '